import * as fs from 'fs';
import * as path from 'path';

// Master list of top tech startups/companies
const companies = [
  // Greenhouse ATS
  { id: '1password', name: '1Password', atsType: 'greenhouse' },
  { id: 'abnormal', name: 'Abnormal Security', atsType: 'greenhouse' },
  { id: 'acorns', name: 'Acorns', atsType: 'greenhouse' },
  { id: 'affirm', name: 'Affirm', atsType: 'greenhouse' },
  { id: 'algolia', name: 'Algolia', atsType: 'greenhouse' },
  { id: 'alteryx', name: 'Alteryx', atsType: 'greenhouse' },
  { id: 'ampere', name: 'Ampere', atsType: 'greenhouse' },
  { id: 'amplitude', name: 'Amplitude', atsType: 'greenhouse' },
  { id: 'anchor', name: 'Anchor', atsType: 'greenhouse' },
  { id: 'anduril', name: 'Anduril', atsType: 'greenhouse' },
  { id: 'anthropic', name: 'Anthropic', atsType: 'greenhouse' },
  { id: 'apollo', name: 'Apollo GraphQL', atsType: 'greenhouse' },
  { id: 'appian', name: 'Appian', atsType: 'greenhouse' },
  { id: 'applovin', name: 'AppLovin', atsType: 'greenhouse' },
  { id: 'appsflyer', name: 'AppsFlyer', atsType: 'greenhouse' },
  { id: 'asana', name: 'Asana', atsType: 'greenhouse' },
  { id: 'astronomer', name: 'Astronomer', atsType: 'greenhouse' },
  { id: 'auth0', name: 'Auth0', atsType: 'greenhouse' },
  { id: 'automattic', name: 'Automattic', atsType: 'greenhouse' },
  { id: 'aviatrix', name: 'Aviatrix', atsType: 'greenhouse' },
  { id: 'aws', name: 'AWS', atsType: 'greenhouse' },
  { id: 'axios', name: 'Axios', atsType: 'greenhouse' },
  { id: 'bamboohr', name: 'BambooHR', atsType: 'greenhouse' },
  { id: 'betterment', name: 'Betterment', atsType: 'greenhouse' },
  { id: 'bigcommerce', name: 'BigCommerce', atsType: 'greenhouse' },
  { id: 'bird', name: 'Bird', atsType: 'greenhouse' },
  { id: 'bitly', name: 'Bitly', atsType: 'greenhouse' },
  { id: 'blend', name: 'Blend', atsType: 'greenhouse' },
  { id: 'bluebeam', name: 'Bluebeam', atsType: 'greenhouse' },
  { id: 'box', name: 'Box', atsType: 'greenhouse' },
  { id: 'braze', name: 'Braze', atsType: 'greenhouse' },
  { id: 'brex', name: 'Brex', atsType: 'greenhouse' },
  { id: 'bucket', name: 'Bucket', atsType: 'greenhouse' },
  { id: 'buffer', name: 'Buffer', atsType: 'greenhouse' },
  { id: 'calendly', name: 'Calendly', atsType: 'greenhouse' },
  { id: 'calm', name: 'Calm', atsType: 'greenhouse' },
  { id: 'canva', name: 'Canva', atsType: 'greenhouse' },
  { id: 'carta', name: 'Carta', atsType: 'greenhouse' },
  { id: 'cashapp', name: 'Cash App', atsType: 'greenhouse' },
  { id: 'chainlink', name: 'Chainlink', atsType: 'greenhouse' },
  { id: 'chime', name: 'Chime', atsType: 'greenhouse' },
  { id: 'circleci', name: 'CircleCI', atsType: 'greenhouse' },
  { id: 'clearbit', name: 'Clearbit', atsType: 'greenhouse' },
  { id: 'clever', name: 'Clever', atsType: 'greenhouse' },
  { id: 'clickup', name: 'ClickUp', atsType: 'greenhouse' },
  { id: 'cloudflare', name: 'Cloudflare', atsType: 'greenhouse' },
  { id: 'coda', name: 'Coda', atsType: 'greenhouse' },
  { id: 'coinbase', name: 'Coinbase', atsType: 'greenhouse' },
  { id: 'compass', name: 'Compass', atsType: 'greenhouse' },
  { id: 'confluent', name: 'Confluent', atsType: 'greenhouse' },
  { id: 'contentful', name: 'Contentful', atsType: 'greenhouse' },
  { id: 'coursera', name: 'Coursera', atsType: 'greenhouse' },
  { id: 'crowdstrike', name: 'CrowdStrike', atsType: 'greenhouse' },
  { id: 'cruise', name: 'Cruise', atsType: 'greenhouse' },
  { id: 'customerio', name: 'Customer.io', atsType: 'greenhouse' },
  { id: 'datadog', name: 'Datadog', atsType: 'greenhouse' },
  { id: 'databricks', name: 'Databricks', atsType: 'greenhouse' },
  { id: 'deel', name: 'Deel', atsType: 'greenhouse' },
  { id: 'digitalocean', name: 'DigitalOcean', atsType: 'greenhouse' },
  { id: 'discord', name: 'Discord', atsType: 'greenhouse' },
  { id: 'docker', name: 'Docker', atsType: 'greenhouse' },
  { id: 'doordash', name: 'DoorDash', atsType: 'greenhouse' },
  { id: 'dropbox', name: 'Dropbox', atsType: 'greenhouse' },
  { id: 'duolingo', name: 'Duolingo', atsType: 'greenhouse' },
  { id: 'elastic', name: 'Elastic', atsType: 'greenhouse' },
  { id: 'epicgames', name: 'Epic Games', atsType: 'greenhouse' },
  { id: 'eventbrite', name: 'Eventbrite', atsType: 'greenhouse' },
  { id: 'evernote', name: 'Evernote', atsType: 'greenhouse' },
  { id: 'faire', name: 'Faire', atsType: 'greenhouse' },
  { id: 'fastly', name: 'Fastly', atsType: 'greenhouse' },
  { id: 'figma', name: 'Figma', atsType: 'greenhouse' },
  { id: 'fivetran', name: 'Fivetran', atsType: 'greenhouse' },
  { id: 'flexport', name: 'Flexport', atsType: 'greenhouse' },
  { id: 'flyio', name: 'Fly.io', atsType: 'greenhouse' },
  { id: 'formstack', name: 'Formstack', atsType: 'greenhouse' },
  { id: 'framer', name: 'Framer', atsType: 'greenhouse' },
  { id: 'gemini', name: 'Gemini', atsType: 'greenhouse' },
  { id: 'github', name: 'GitHub', atsType: 'greenhouse' },
  { id: 'gitlab', name: 'GitLab', atsType: 'greenhouse' },
  { id: 'glassdoor', name: 'Glassdoor', atsType: 'greenhouse' },
  { id: 'gong', name: 'Gong', atsType: 'greenhouse' },
  { id: 'grammarly', name: 'Grammarly', atsType: 'greenhouse' },
  { id: 'grafana', name: 'Grafana', atsType: 'greenhouse' },
  { id: 'grubhub', name: 'Grubhub', atsType: 'greenhouse' },
  { id: 'guild', name: 'Guild', atsType: 'greenhouse' },
  { id: 'gusto', name: 'Gusto', atsType: 'greenhouse' },
  { id: 'hashicorp', name: 'HashiCorp', atsType: 'greenhouse' },
  { id: 'headspace', name: 'Headspace', atsType: 'greenhouse' },
  { id: 'heaptv', name: 'Heap', atsType: 'greenhouse' },
  { id: 'hellosign', name: 'HelloSign', atsType: 'greenhouse' },
  { id: 'heroku', name: 'Heroku', atsType: 'greenhouse' },
  { id: 'hootsuite', name: 'Hootsuite', atsType: 'greenhouse' },
  { id: 'hopin', name: 'Hopin', atsType: 'greenhouse' },
  { id: 'hotjar', name: 'Hotjar', atsType: 'greenhouse' },
  { id: 'hubspot', name: 'HubSpot', atsType: 'greenhouse' },
  { id: 'huggingface', name: 'Hugging Face', atsType: 'greenhouse' },
  { id: 'impossible', name: 'Impossible Foods', atsType: 'greenhouse' },
  { id: 'invision', name: 'InVision', atsType: 'greenhouse' },
  { id: 'ironclad', name: 'Ironclad', atsType: 'greenhouse' },
  { id: 'jasper', name: 'Jasper', atsType: 'greenhouse' },
  { id: 'kaltura', name: 'Kaltura', atsType: 'greenhouse' },
  { id: 'khanacademy', name: 'Khan Academy', atsType: 'greenhouse' },
  { id: 'kickstarter', name: 'Kickstarter', atsType: 'greenhouse' },
  { id: 'klarna', name: 'Klarna', atsType: 'greenhouse' },
  { id: 'kraken', name: 'Kraken', atsType: 'greenhouse' },
  { id: 'lattice', name: 'Lattice', atsType: 'greenhouse' },
  { id: 'launchdarkly', name: 'LaunchDarkly', atsType: 'greenhouse' },
  { id: 'lemonade', name: 'Lemonade', atsType: 'greenhouse' },
  { id: 'linear', name: 'Linear', atsType: 'greenhouse' },
  { id: 'linktree', name: 'Linktree', atsType: 'greenhouse' },
  { id: 'lucid', name: 'Lucid', atsType: 'greenhouse' },
  { id: 'loom', name: 'Loom', atsType: 'greenhouse' },
  { id: 'lyft', name: 'Lyft', atsType: 'greenhouse' },
  { id: 'mailchimp', name: 'Mailchimp', atsType: 'greenhouse' },
  { id: 'mapbox', name: 'Mapbox', atsType: 'greenhouse' },
  { id: 'masterclass', name: 'MasterClass', atsType: 'greenhouse' },
  { id: 'mattermatter', name: 'Mattermost', atsType: 'greenhouse' },
  { id: 'medium', name: 'Medium', atsType: 'greenhouse' },
  { id: 'miro', name: 'Miro', atsType: 'greenhouse' },
  { id: 'mixpanel', name: 'Mixpanel', atsType: 'greenhouse' },
  { id: 'monday', name: 'Monday.com', atsType: 'greenhouse' },
  { id: 'mongodb', name: 'MongoDB', atsType: 'greenhouse' },
  { id: 'mozilla', name: 'Mozilla', atsType: 'greenhouse' },
  { id: 'mux', name: 'Mux', atsType: 'greenhouse' },
  { id: 'neon', name: 'Neon', atsType: 'greenhouse' },
  { id: 'netlify', name: 'Netlify', atsType: 'greenhouse' },
  { id: 'nextdoor', name: 'Nextdoor', atsType: 'greenhouse' },
  { id: 'nintendo', name: 'Nintendo', atsType: 'greenhouse' },
  { id: 'notion', name: 'Notion', atsType: 'greenhouse' },
  { id: 'nubank', name: 'Nubank', atsType: 'greenhouse' },
  { id: 'okta', name: 'Okta', atsType: 'greenhouse' },
  { id: 'openai', name: 'OpenAI', atsType: 'greenhouse' },
  { id: 'opensea', name: 'OpenSea', atsType: 'greenhouse' },
  { id: 'optimizely', name: 'Optimizely', atsType: 'greenhouse' },
  { id: 'oura', name: 'Oura', atsType: 'greenhouse' },
  { id: 'outreach', name: 'Outreach', atsType: 'greenhouse' },
  { id: 'patreon', name: 'Patreon', atsType: 'greenhouse' },
  { id: 'peloton', name: 'Peloton', atsType: 'greenhouse' },
  { id: 'pinterest', name: 'Pinterest', atsType: 'greenhouse' },
  { id: 'plaid', name: 'Plaid', atsType: 'greenhouse' },
  { id: 'planetscale', name: 'PlanetScale', atsType: 'greenhouse' },
  { id: 'pluto', name: 'Pluto TV', atsType: 'greenhouse' },
  { id: 'postman', name: 'Postman', atsType: 'greenhouse' },
  { id: 'postscript', name: 'Postscript', atsType: 'greenhouse' },
  { id: 'prisma', name: 'Prisma', atsType: 'greenhouse' },
  { id: 'qualtrics', name: 'Qualtrics', atsType: 'greenhouse' },
  { id: 'quora', name: 'Quora', atsType: 'greenhouse' },
  { id: 'ramp', name: 'Ramp', atsType: 'greenhouse' },
  { id: 'raycast', name: 'Raycast', atsType: 'greenhouse' },
  { id: 'reddit', name: 'Reddit', atsType: 'greenhouse' },
  { id: 'redfin', name: 'Redfin', atsType: 'greenhouse' },
  { id: 'remote', name: 'Remote', atsType: 'greenhouse' },
  { id: 'render', name: 'Render', atsType: 'greenhouse' },
  { id: 'replit', name: 'Replit', atsType: 'greenhouse' },
  { id: 'retool', name: 'Retool', atsType: 'greenhouse' },
  { id: 'ringcentral', name: 'RingCentral', atsType: 'greenhouse' },
  { id: 'rippling', name: 'Rippling', atsType: 'greenhouse' },
  { id: 'robinhood', name: 'Robinhood', atsType: 'greenhouse' },
  { id: 'roblox', name: 'Roblox', atsType: 'greenhouse' },
  { id: 'roku', name: 'Roku', atsType: 'greenhouse' },
  { id: 'rubrik', name: 'Rubrik', atsType: 'greenhouse' },
  { id: 'scale', name: 'Scale AI', atsType: 'greenhouse' },
  { id: 'segment', name: 'Segment', atsType: 'greenhouse' },
  { id: 'sendgrid', name: 'SendGrid', atsType: 'greenhouse' },
  { id: 'sentry', name: 'Sentry', atsType: 'greenhouse' },
  { id: 'shopify', name: 'Shopify', atsType: 'greenhouse' },
  { id: 'slack', name: 'Slack', atsType: 'greenhouse' },
  { id: 'smartsheet', name: 'Smartsheet', atsType: 'greenhouse' },
  { id: 'snowflake', name: 'Snowflake', atsType: 'greenhouse' },
  { id: 'sofi', name: 'SoFi', atsType: 'greenhouse' },
  { id: 'splunk', name: 'Splunk', atsType: 'greenhouse' },
  { id: 'spotify', name: 'Spotify', atsType: 'greenhouse' },
  { id: 'squarespace', name: 'Squarespace', atsType: 'greenhouse' },
  { id: 'stockx', name: 'StockX', atsType: 'greenhouse' },
  { id: 'stripe', name: 'Stripe', atsType: 'greenhouse' },
  { id: 'substack', name: 'Substack', atsType: 'greenhouse' },
  { id: 'supabase', name: 'Supabase', atsType: 'greenhouse' },
  { id: 'superhuman', name: 'Superhuman', atsType: 'greenhouse' },
  { id: 'tailscale', name: 'Tailscale', atsType: 'greenhouse' },
  { id: 'taskrabbit', name: 'TaskRabbit', atsType: 'greenhouse' },
  { id: 'thoughtspot', name: 'ThoughtSpot', atsType: 'greenhouse' },
  { id: 'thumbtack', name: 'Thumbtack', atsType: 'greenhouse' },
  { id: 'toast', name: 'Toast', atsType: 'greenhouse' },
  { id: 'trello', name: 'Trello', atsType: 'greenhouse' },
  { id: 'turo', name: 'Turo', atsType: 'greenhouse' },
  { id: 'twilio', name: 'Twilio', atsType: 'greenhouse' },
  { id: 'twitch', name: 'Twitch', atsType: 'greenhouse' },
  { id: 'typeform', name: 'Typeform', atsType: 'greenhouse' },
  { id: 'ubereats', name: 'UberEats', atsType: 'greenhouse' },
  { id: 'udacity', name: 'Udacity', atsType: 'greenhouse' },
  { id: 'unity', name: 'Unity', atsType: 'greenhouse' },
  { id: 'upwork', name: 'Upwork', atsType: 'greenhouse' },
  { id: 'vercel', name: 'Vercel', atsType: 'greenhouse' },
  { id: 'vimeo', name: 'Vimeo', atsType: 'greenhouse' },
  { id: 'vox', name: 'Vox Media', atsType: 'greenhouse' },
  { id: 'wayfair', name: 'Wayfair', atsType: 'greenhouse' },
  { id: 'wealthfront', name: 'Wealthfront', atsType: 'greenhouse' },
  { id: 'webflow', name: 'Webflow', atsType: 'greenhouse' },
  { id: 'whatnot', name: 'Whatnot', atsType: 'greenhouse' },
  { id: 'wolt', name: 'Wolt', atsType: 'greenhouse' },
  { id: 'yelp', name: 'Yelp', atsType: 'greenhouse' },
  { id: 'zapier', name: 'Zapier', atsType: 'greenhouse' },
  { id: 'zendesk', name: 'Zendesk', atsType: 'greenhouse' },
  { id: 'zillow', name: 'Zillow', atsType: 'greenhouse' },
  { id: 'ziprecruiter', name: 'ZipRecruiter', atsType: 'greenhouse' },
  { id: 'zoom', name: 'Zoom', atsType: 'greenhouse' },
  { id: 'zscaler', name: 'Zscaler', atsType: 'greenhouse' },

  // Lever ATS
  { id: 'andela', name: 'Andela', atsType: 'lever' },
  { id: 'articulate', name: 'Articulate', atsType: 'lever' },
  { id: 'auth0', name: 'Auth0', atsType: 'lever' },
  { id: 'benchling', name: 'Benchling', atsType: 'lever' },
  { id: 'canary', name: 'Canary', atsType: 'lever' },
  { id: 'coursera', name: 'Coursera', atsType: 'lever' },
  { id: 'cultureamp', name: 'Culture Amp', atsType: 'lever' },
  { id: 'dbtlabs', name: 'dbt Labs', atsType: 'lever' },
  { id: 'deel', name: 'Deel', atsType: 'lever' },
  { id: 'figma', name: 'Figma', atsType: 'lever' },
  { id: 'front', name: 'Front', atsType: 'lever' },
  { id: 'gocardless', name: 'GoCardless', atsType: 'lever' },
  { id: 'grammarly', name: 'Grammarly', atsType: 'lever' },
  { id: 'gusto', name: 'Gusto', atsType: 'lever' },
  { id: 'hightouch', name: 'Hightouch', atsType: 'lever' },
  { id: 'hopper', name: 'Hopper', atsType: 'lever' },
  { id: 'invision', name: 'InVision', atsType: 'lever' },
  { id: 'kinsta', name: 'Kinsta', atsType: 'lever' },
  { id: 'klarna', name: 'Klarna', atsType: 'lever' },
  { id: 'lattice', name: 'Lattice', atsType: 'lever' },
  { id: 'launchdarkly', name: 'LaunchDarkly', atsType: 'lever' },
  { id: 'lever', name: 'Lever', atsType: 'lever' },
  { id: 'loom', name: 'Loom', atsType: 'lever' },
  { id: 'marvel', name: 'Marvel', atsType: 'lever' },
  { id: 'masterclass', name: 'Masterclass', atsType: 'lever' },
  { id: 'monzo', name: 'Monzo', atsType: 'lever' },
  { id: 'notion', name: 'Notion', atsType: 'lever' },
  { id: 'outreach', name: 'Outreach', atsType: 'lever' },
  { id: 'papayaglobal', name: 'Papaya Global', atsType: 'lever' },
  { id: 'pitch', name: 'Pitch', atsType: 'lever' },
  { id: 'plaid', name: 'Plaid', atsType: 'lever' },
  { id: 'postman', name: 'Postman', atsType: 'lever' },
  { id: 'quora', name: 'Quora', atsType: 'lever' },
  { id: 'ramp', name: 'Ramp', atsType: 'lever' },
  { id: 'replit', name: 'Replit', atsType: 'lever' },
  { id: 'retool', name: 'Retool', atsType: 'lever' },
  { id: 'rippling', name: 'Rippling', atsType: 'lever' },
  { id: 'roblox', name: 'Roblox', atsType: 'lever' },
  { id: 'scale', name: 'Scale AI', atsType: 'lever' },
  { id: 'sendbird', name: 'Sendbird', atsType: 'lever' },
  { id: 'shopify', name: 'Shopify', atsType: 'lever' },
  { id: 'snowflake', name: 'Snowflake', atsType: 'lever' },
  { id: 'spotify', name: 'Spotify', atsType: 'lever' },
  { id: 'strava', name: 'Strava', atsType: 'lever' },
  { id: 'stripe', name: 'Stripe', atsType: 'lever' },
  { id: 'substack', name: 'Substack', atsType: 'lever' },
  { id: 'superhuman', name: 'Superhuman', atsType: 'lever' },
  { id: 'taskrabbit', name: 'TaskRabbit', atsType: 'lever' },
  { id: 'thoughtspot', name: 'Thoughtspot', atsType: 'lever' },
  { id: 'trello', name: 'Trello', atsType: 'lever' },
  { id: 'typeform', name: 'Typeform', atsType: 'lever' },
  { id: 'udacity', name: 'Udacity', atsType: 'lever' },
  { id: 'vimeo', name: 'Vimeo', atsType: 'lever' },
  { id: 'webflow', name: 'Webflow', atsType: 'lever' },
  { id: 'yelp', name: 'Yelp', atsType: 'lever' },
  { id: 'zapier', name: 'Zapier', atsType: 'lever' },
  { id: 'zendesk', name: 'Zendesk', atsType: 'lever' },

  // Ashby ATS
  { id: 'anthropic', name: 'Anthropic', atsType: 'ashby' },
  { id: 'coda', name: 'Coda', atsType: 'ashby' },
  { id: 'coinbase', name: 'Coinbase', atsType: 'ashby' },
  { id: 'crux', name: 'Crux', atsType: 'ashby' },
  { id: 'dbtlabs', name: 'dbt Labs', atsType: 'ashby' },
  { id: 'decagon', name: 'Decagon', atsType: 'ashby' },
  { id: 'dydx', name: 'dYdX', atsType: 'ashby' },
  { id: 'eliseai', name: 'EliseAI', atsType: 'ashby' },
  { id: 'equi', name: 'Equi', atsType: 'ashby' },
  { id: 'farcaster', name: 'Farcaster', atsType: 'ashby' },
  { id: 'felix', name: 'Felix', atsType: 'ashby' },
  { id: 'fossa', name: 'Fossa', atsType: 'ashby' },
  { id: 'gopuff', name: 'Gopuff', atsType: 'ashby' },
  { id: 'gumroad', name: 'Gumroad', atsType: 'ashby' },
  { id: 'harvey', name: 'Harvey', atsType: 'ashby' },
  { id: 'hightouch', name: 'Hightouch', atsType: 'ashby' },
  { id: 'jasper', name: 'Jasper', atsType: 'ashby' },
  { id: 'langchain', name: 'LangChain', atsType: 'ashby' },
  { id: 'levels', name: 'Levels', atsType: 'ashby' },
  { id: 'linear', name: 'Linear', atsType: 'ashby' },
  { id: 'mercury', name: 'Mercury', atsType: 'ashby' },
  { id: 'midjourney', name: 'Midjourney', atsType: 'ashby' },
  { id: 'mistral', name: 'Mistral AI', atsType: 'ashby' },
  { id: 'modal', name: 'Modal', atsType: 'ashby' },
  { id: 'monarch', name: 'Monarch Money', atsType: 'ashby' },
  { id: 'mux', name: 'Mux', atsType: 'ashby' },
  { id: 'nebius', name: 'Nebius', atsType: 'ashby' },
  { id: 'notion', name: 'Notion', atsType: 'ashby' },
  { id: 'nuro', name: 'Nuro', atsType: 'ashby' },
  { id: 'observable', name: 'Observable', atsType: 'ashby' },
  { id: 'perplexity', name: 'Perplexity', atsType: 'ashby' },
  { id: 'pinecone', name: 'Pinecone', atsType: 'ashby' },
  { id: 'posthog', name: 'PostHog', atsType: 'ashby' },
  { id: 'pylon', name: 'Pylon', atsType: 'ashby' },
  { id: 'ramp', name: 'Ramp', atsType: 'ashby' },
  { id: 'raycast', name: 'Raycast', atsType: 'ashby' },
  { id: 'replicate', name: 'Replicate', atsType: 'ashby' },
  { id: 'resend', name: 'Resend', atsType: 'ashby' },
  { id: 'retool', name: 'Retool', atsType: 'ashby' },
  { id: 'runway', name: 'Runway', atsType: 'ashby' },
  { id: 'scale', name: 'Scale AI', atsType: 'ashby' },
  { id: 'sentry', name: 'Sentry', atsType: 'ashby' },
  { id: 'supaglue', name: 'Supaglue', atsType: 'ashby' },
  { id: 'tavily', name: 'Tavily', atsType: 'ashby' },
  { id: 'together', name: 'Together AI', atsType: 'ashby' },
  { id: 'tome', name: 'Tome', atsType: 'ashby' },
  { id: 'vercel', name: 'Vercel', atsType: 'ashby' },
  { id: 'warp', name: 'Warp', atsType: 'ashby' },
  { id: 'ycombinator', name: 'Y Combinator', atsType: 'ashby' },
  { id: 'zapier', name: 'Zapier', atsType: 'ashby' },
  { id: 'zepto', name: 'Zepto', atsType: 'ashby' },
  { id: 'zoom', name: 'Zoom', atsType: 'ashby' },
];

async function generateConfigs() {
  const configsDir = path.join(process.cwd(), 'scraper', 'configs');
  
  if (!fs.existsSync(configsDir)) {
    fs.mkdirSync(configsDir, { recursive: true });
  }

  let count = 0;

  for (const company of companies) {
    const configPath = path.join(configsDir, `${company.id}.json`);
    
    // Skip if already exists so we don't overwrite custom configurations (the 171)
    if (fs.existsSync(configPath)) {
      continue;
    }

    let careersUrl = '';
    if (company.atsType === 'greenhouse') {
      careersUrl = `https://boards.greenhouse.io/${company.id}`;
    } else if (company.atsType === 'lever') {
      careersUrl = `https://jobs.lever.co/${company.id}`;
    } else if (company.atsType === 'ashby') {
      careersUrl = `https://jobs.ashbyhq.com/${company.id}`;
    }

    const config = {
      companyName: company.name,
      careersUrl,
      atsType: company.atsType
    };

    fs.writeFileSync(configPath, JSON.stringify(config, null, 2));
    count++;
  }

  console.log(`Successfully generated ${count} new ATS configuration files.`);
}

generateConfigs().catch(console.error);
