export const TOP_COMPANIES = [
  "Stripe", "Airbnb", "Netflix", "Uber", "Lyft", "Shopify", "Vercel", "Supabase", "Linear", "Notion",
  "Figma", "Canva", "Slack", "Discord", "GitHub", "GitLab", "Atlassian", "Twilio", "SendGrid", "Plaid",
  "Coinbase", "Kraken", "Gemini", "OpenAI", "Anthropic", "Midjourney", "HuggingFace", "Scale AI", "Databricks", "Snowflake",
  "MongoDB", "Elastic", "Redis", "Neon", "PlanetScale", "Cloudflare", "Fastly", "Netlify", "Heroku",
  "DigitalOcean", "Linode", "Vultr", "AWS", "Google", "Microsoft", "Apple", "Meta", "Amazon", "Tesla",
  "SpaceX", "Rivian", "Lucid", "Cruise", "Waymo", "Zoox", "Nuro", "Aurora", "TuSimple", "Embark",
  "DoorDash", "Instacart", "Grubhub", "Postmates", "Deliveroo", "Glovo", "Rappi", "Gopuff", "Getir",
  "Zillow", "Redfin", "Opendoor", "Compass", "Expedia", "Booking.com", "Tripadvisor", "Skyscanner", "Kayak", "Trivago",
  "Spotify", "SoundCloud", "Tidal", "Pandora", "SiriusXM", "Audible", "Pocket Casts", "Overcast", "Castro", "Breaker",
  "Pinterest", "Snapchat", "TikTok", "ByteDance", "Tencent", "Alibaba", "Baidu", "JD.com", "Meituan", "Didi",
  "Robinhood", "Wealthfront", "Betterment", "Acorns", "Stash", "Public", "Webull", "eToro", "Revolut", "Monzo",
  "N26", "Chime", "Varo", "Current", "Aspiration", "Step", "Greenlight", "Square", "Block", "Cash App",
  "Affirm", "Klarna", "Afterpay", "Sezzle", "Zip", "PayPal", "Venmo", "Zelle", "Google Pay",
  "Roku", "Hulu", "Disney", "HBO", "Paramount", "Peacock", "Crunchyroll", "Funimation", "Twitch", "YouTube",
  "Epic Games", "Unity", "Roblox", "Valve", "EA", "Activision", "Blizzard", "Riot Games", "Bungie", "Naughty Dog",
  "Sony", "Nintendo", "Sega", "Capcom", "Square Enix", "Bandai Namco", "Konami", "Koei Tecmo", "Atlus", "Level-5",
  "Samsung", "LG", "Panasonic", "Toshiba", "Sharp", "Philips", "Vizio", "TCL", "Hisense",
  "Intel", "AMD", "Nvidia", "Qualcomm", "Broadcom", "Texas Instruments", "Micron", "Western Digital", "Seagate", "Kingston",
  "Dell", "HP", "Lenovo", "Asus", "Acer", "MSI", "Razer", "Corsair", "Logitech", "SteelSeries",
  "Cisco", "Juniper", "Arista", "Palo Alto Networks", "Fortinet", "Check Point", "FireEye", "CrowdStrike", "Okta", "Auth0",
  "Splunk", "Datadog", "New Relic", "AppDynamics", "Dynatrace", "SolarWinds", "Nagios", "Zabbix", "Prometheus", "Grafana",
  "Docker", "Kubernetes", "HashiCorp", "Terraform", "Vault", "Consul", "Nomad", "Vagrant", "Packer", "Waypoint",
  "Salesforce", "HubSpot", "Zendesk", "Intercom", "Drift", "Freshworks", "Zoho", "Pipedrive", "Copper", "Insightly",
  "Mailchimp", "Constant Contact", "AWeber", "ConvertKit", "ActiveCampaign", "Drip", "MailerLite", "Sendinblue", "Omnisend", "Klaviyo",
  "BigCommerce", "WooCommerce", "Magento", "PrestaShop", "OpenCart", "Wix", "Squarespace", "Weebly", "Webflow",
  "WordPress", "Ghost", "Medium", "Substack", "Patreon", "OnlyFans", "Instagram",
  "Asana", "Trello", "Monday", "ClickUp", "Wrike", "Smartsheet", "Airtable", "Coda", "Basecamp",
  "Zoom", "Webex", "Google Meet", "Microsoft Teams", "Skype", "Mattermost", "Rocket.Chat", "Zulip",
  "Dropbox", "Box", "Google Drive", "OneDrive", "iCloud", "Mega", "MediaFire", "WeTransfer", "Send Anywhere", "Tresorit",
  "1Password", "LastPass", "Bitwarden", "Dashlane", "Keeper", "RoboForm", "Enpass", "KeePass", "NordPass", "Sticky Password",
  "NordVPN", "ExpressVPN", "CyberGhost", "Surfshark", "ProtonVPN", "Mullvad", "PIA", "Windscribe", "TunnelBear", "VyprVPN",
  "Brave", "Vivaldi", "Opera", "Firefox", "Chrome", "Edge", "Safari", "Tor", "DuckDuckGo", "Ecosia",
  "Coursera", "Udemy", "edX", "Skillshare", "MasterClass", "Pluralsight", "LinkedIn Learning", "Treehouse", "Codecademy", "Udacity",
  "Duolingo", "Babbel", "Rosetta Stone", "Memrise", "Busuu", "Mondly", "Drops", "Lingvist", "Clozemaster", "Pimsleur",
  "Peloton", "Tonal", "Mirror", "Tempo", "Obe", "Apple Fitness", "Fitbit", "Garmin", "Whoop", "Oura",
  "Strava", "Runkeeper", "MapMyRun", "Nike Run Club", "Adidas Running", "AllTrails", "Komoot", "Relive", "Trailforks", "Wikiloc",
  "MyFitnessPal", "Lose It", "Cronometer", "FatSecret", "YAZIO", "Lifesum", "Noom", "Weight Watchers", "Kurbo", "Fooducate",
  "Headspace", "Calm", "Insight Timer", "Waking Up", "Ten Percent Happier", "Simple Habit", "Breethe", "Sattva", "Medito", "Oak",
  "BetterHelp", "Talkspace", "Amwell", "MDLive", "Doctor on Demand", "Teladoc", "Zocdoc", "Healthgrades", "Vitals", "WebMD",
  "GoodRx", "SingleCare", "Blink Health", "ScriptSave", "RxSaver", "WellRx", "Optum Perks", "FamilyWize", "NeedyMeds", "RxAssist",
  "23andMe", "Ancestry", "MyHeritage", "FamilyTreeDNA", "Living DNA", "Nebula Genomics", "Veritas Genetics", "Color", "Invitae", "Counsyl",
  "Oscar", "Clover", "Devoted", "Alignment", "Bright", "Friday", "Sana", "Bind", "Gravie", "Decent",
  "Gusto", "Rippling", "Justworks", "Zenefits", "BambooHR", "Workday", "ADP", "Paychex", "TriNet", "Insperity",
  "Brex", "Ramp", "Divvy", "Airbase", "Teampay", "Spendesk", "Pleo", "Soldo", "Expensify", "Concur",
  "Adyen", "Braintree", "Checkout.com", "Mollie", "Toast", "Lightspeed", "Vend",
  "Render", "Fly.io", "Railway",
  "Google Cloud", "Microsoft Azure", "IBM Cloud", "Oracle Cloud", "Alibaba Cloud", "Tencent Cloud", "Baidu Cloud", "Huawei Cloud", "Scaleway",
  "Cloudera", "Hortonworks", "MapR", "Talend", "Informatica", "Alteryx", "Tableau", "Looker",
  "DeepMind", "Cohere", "AI21", "Inflection", "Adept", "Character.AI", "Stability AI",
  "Runway", "Descript", "Synthesia", "MURF", "WellSaid", "Resemble", "Replica", "Sonantic", "Lovo", "Voiceflow"
];
